//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libreria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class carrito
    {
        public int id { get; set; }
        public string imagen { get; set; }
        public string nombre { get; set; }
        public double precio { get; set; }
        public string descripcion { get; set; }
        public int cantidad { get; set; }
        public int id_usuario { get; set; }
        public int id_producto { get; set; }
    }
}
