//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libreria.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBLibreriaEntity : DbContext
    {
        public DBLibreriaEntity()
            : base("name=DBLibreriaEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<carrito> carrito { get; set; }
        public DbSet<productos> productos { get; set; }
        public DbSet<proveedores> proveedores { get; set; }
        public DbSet<usuarios> usuarios { get; set; }
    }
}
